logging:
  json_format: false
  level: trace

api:
  enabled: true
  port: 8080

workers:
  enabled: true
  count: 1
  data_directory: ./data/worker

blob_store:
  type: memory

data_sink:
  type: memory

queue:
  type: memory

database:
  type: static


databases:
  - type: redshift
    api_keys:
      - test_api_key
    settings:
      delete_from_s3: true

      # Redshift connection
      redshift_host: myredshiftcluster.amazonaws.com 
      redshift_port: 5439 
      redshift_user: myuser 
      redshift_password: mypassword 
      redshift_dbname: mydb

      # S3 bucket
      s3_region: "us-east-1"
      s3_access_key_id: "ACCESS_KEY_ID"
      s3_secret_access_key: "SECRET_ACCESS_KEY"
      s3_bucket: "bucket_name"